# Project Euler
# Problem # 2
#
# Description: Each new term in the Fibonacci sequence is generated by adding 
#              the previous two terms. By starting with 1 and 2, the first 10 
#              terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#              Find the sum of all the even-valued terms in the sequence which 
#              do not exceed four million.
#
# URL:         http://projecteuler.net/index.php?section=problems&id=2

def fib(i,j)
  i + j
end

max = 40_00_000
seq = [1, 2]
sum = 0

seq << fib(seq[-2],seq [-1]) while (seq[-2] < max && seq [-1] < max)

seq.reject { |item| item % 2 != 0 }.each { |evens| sum += evens}
puts "The sum of all even-valued terms in the sequence which do not exceed #{max} is #{sum}"
